# Generated by Django 4.0.3 on 2022-03-28 12:53

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_car_condition_car_make_car_price_car_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1000'), default_currency='USD', max_digits=6, validators=[djmoney.models.validators.MinMoneyValidator(4), djmoney.models.validators.MaxMoneyValidator(6)], verbose_name='Asking Price'),
        ),
    ]
