# Generated by Django 4.0.3 on 2022-03-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0006_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('p', 'Poor'), ('f', 'Fair'), ('g', 'Good'), ('e', 'Excellence')], default='p', max_length=8),
        ),
    ]
