# Generated by Django 4.0.3 on 2022-03-29 05:52

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0009_alter_car_condition_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1000'), default_currency='USD', help_text='$1000 - $100,000', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(1000), djmoney.models.validators.MaxMoneyValidator(100000)], verbose_name='Asking Price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year'),
        ),
    ]
