# Generated by Django 4.0.3 on 2022-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0010_alter_car_price_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Select', 'Select'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellence')], default='Select', max_length=20),
        ),
    ]
