# Generated by Django 4.0.3 on 2022-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0013_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=50),
        ),
    ]
