# Generated by Django 4.0.3 on 2022-04-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0014_car_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
    ]
