# Generated by Django 4.0.3 on 2022-04-04 12:33

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0016_car_commission_car_commission_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='commission_currency',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='Net_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
    ]
